In [1]:
# merge, concat, pivot, melt - dbms mariadb

In [2]:
import pandas as pd

In [3]:
s1 = pd.DataFrame([[10, 20], [30, 40], [50, 60], [70, 80]], columns=['수학', '과학'] )
s1

   수학  과학
0  10  20
1  30  40
2  50  60
3  70  80

In [ ]:
s2 = pd.DataFrame([[5, 6], [13, 15]], columns=['과학', '수학'])
s2

   과학  수학
0   5   6
1  13  15

In [ ]:
#axis가 붙이는 방향을 나타냄
pd.concat([s1, s2], axis=0)

   수학  과학
0  10  20
1  30  40
2  50  60
3  70  80
0   6   5
1  15  13

In [ ]:
s3 = pd.DataFrame([[5, 87], [15, 90]], columns=['과학', '역사'])
s3

   과학  역사
0   5  87
1  15  90

In [ ]:
# 겹치는 부분이 없을 경우 NaN으로 처리
pd.concat([s1, s3])

     수학  과학    역사
0  10.0  20   NaN
1  30.0  40   NaN
2  50.0  60   NaN
3  70.0  80   NaN
0   NaN   5  87.0
1   NaN  15  90.0

In [ ]:
#join옵션을 inner로 변경하면 겹치는 부분만 출력
pd.concat([s1, s3], join='inner')

   과학
0  20
1  40
2  60
3  80
0   5
1  15

In [ ]:
#가로 방향으로 붙이기 위한 데이터
s4 = pd.DataFrame([[36, 100], [13, 46], [57, 68], [26, 37]], columns=['역사', '코딩'], index=[1, 2, 3, 0])
s4

   역사   코딩
1  36  100
2  13   46
3  57   68
0  26   37

In [ ]:
#axis=1 옵션으로 가로 방향을 지정
pd.concat([s1, s4], axis=1)

   수학  과학  역사   코딩
0  10  20  26   37
1  30  40  36  100
2  50  60  13   46
3  70  80  57   68

In [ ]:
# 데이터의 크기가 다른 경우
s5 = pd.DataFrame([[36, 25], [13, 46], [57, 68]], columns=['역사', '코딩'], index=[2, 3, 4])
# s5.index = [1, 2, 3]
s5

   역사  코딩
2  36  25
3  13  46
4  57  68

In [ ]:
#inner 옵션을 주면 겹치지 않는 데이터는 삭제
pd.concat([s1, s5], axis=1, join='inner')

   수학  과학  역사  코딩
2  50  60  36  25
3  70  80  13  46

In [ ]:
# concat - index를 기준으로 한 merge와 같다.
# concat 가로 방향으로 붙일 때 index를 기준으로 ...
# merge 는 index말고 컬럼 지정 가능
# [Country LS]   [Country GDP]

# pivot, melt
 - 일반적인 관계형 데이터베이스(DBMS)에서는 다차원의 데이터를 2차원으로 조직화
 - 데이터를 조직화하는 과정에서 다양한 형태가 된다.
 - key의 역할을 하는 부분과 실질적인 value의 역할을 하는 데이터가 구분됨
  - 2차원으로 구성된 value -> melt -> 1차원
  - 1차원 -> pivot -> 2차원

In [ ]:
df = pd.concat([s1, s4], axis=1)
df['학번'] = [1, 2, 3, 4]
df

   수학  과학  역사  코딩  학번
0  10  20  36  25   1
1  30  40  13  46   2
2  50  60  57  68   3
3  70  80  26  37   4

In [ ]:
melted = df.melt(id_vars='학번', value_vars=['수학', '과학', '역사', '코딩'], value_name='점수', var_name='과목')
#melted.columns = ['학번', '과목', '점수']
# melted.rename({'variable':'과목', 'value':'점수'}, axis=1, inplace=True)
melted

    학번  과목  점수
0    1  수학  10
1    2  수학  30
2    3  수학  50
3    4  수학  70
4    1  과학  20
5    2  과학  40
6    3  과학  60
7    4  과학  80
8    1  역사  36
9    2  역사  13
10   3  역사  57
11   4  역사  26
12   1  코딩  25
13   2  코딩  46
14   3  코딩  68
15   4  코딩  37

In [ ]:
pv = melted.pivot(index='학번', columns='과목', values='점수')
pv
pv.reset_index()

과목  학번  과학  수학  역사  코딩
0    1  20  10  36  25
1    2  40  30  13  46
2    3  60  50  57  68
3    4  80  70  26  37

In [ ]:
students = pd.DataFrame({'학번':[1, 2, 3, 5],
                         '이름':['김', '이', '박', '성'],
                         '거주지':['수성', '수성', '화성', '토성']})
students

   학번 이름 거주지
0   1  김  수성
1   2  이  수성
2   3  박  화성
3   5  성  토성

In [ ]:
melted.merge(students, on='학번', how='outer')
# pd.merge(melted, students, on='학번', how='right')

    학번   과목    점수   이름  거주지
0    1   수학  10.0    김   수성
1    1   과학  20.0    김   수성
2    1   역사  36.0    김   수성
3    1   코딩  25.0    김   수성
4    2   수학  30.0    이   수성
5    2   과학  40.0    이   수성
6    2   역사  13.0    이   수성
7    2   코딩  46.0    이   수성
8    3   수학  50.0    박   화성
9    3   과학  60.0    박   화성
10   3   역사  57.0    박   화성
11   3   코딩  68.0    박   화성
12   4   수학  70.0  NaN  NaN
13   4   과학  80.0  NaN  NaN
14   4   역사  26.0  NaN  NaN
15   4   코딩  37.0  NaN  NaN
16   5  NaN   NaN    성   토성