## [ 데이터 필터링 ]
- DataFrame/Series에서 원하는 데이터만 추출
- 불린 인덱싱
- 메서드 isin()
- 메서드 query()

In [1]:
## [1] 모듈 로딩 및 데이터 준비
import pandas as pd

DATA_FILE = '../../DATA/학생관리부.xlsx'

In [2]:
## [2] 데이터 로딩 및 기본 정보 출력
dataDF = pd.read_excel(DATA_FILE, header = 2)
dataDF

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1
2  이길동   1  7   12
3  박길동   3  1    9
4  최길동   2  1   43

In [3]:
## [3] 특정 조건에 맞는 데이터만 추출 즉, 필터링
## [3-1] 석차가 상위 10위까지만 데이터 추출
dataDF.columns[-1]

' 석차'

In [4]:
dataDF[dataDF.columns[-1]]

0     8
1     1
2    12
3     9
4    43
Name:  석차, dtype: int64

In [7]:
## 비교 연산으로 True/False로 구성된 Series
boolSR = dataDF[dataDF.columns[-1]] <=10
boolSR

0     True
1     True
2    False
3     True
4    False
Name:  석차, dtype: bool

In [ ]:
## 상위 10위 안에 있는 데이터만 추출
dataDF[ boolSR ]

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1
3  박길동   3  1    9

In [ ]:
## 상위 10위 밖에 있는 데이터만 추출
## ~ : Not 연산자, 현재 결과를 반대로
dataDF[ ~boolSR ]

    이름  학년  반   석차
2  이길동   1  7   12
4  최길동   2  1   43

In [ ]:
## [3-2] 1학년 중에 상위 10위 안에 들어가는 학생 데이터
##     => 학년 컬럼 ==1,    석차 <= 10  : 2개 조건 모두 만족
dataDF

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1
2  이길동   1  7   12
3  박길동   3  1    9
4  최길동   2  1   43

In [11]:
## columns 속성으로 컬럼명 추출
dataDF.columns[1], dataDF.columns[-1]

('학년', ' 석차')

In [14]:
## ==> 학년 컬럼 == 1
dataDF[dataDF.columns[1]] == 1

0     True
1     True
2     True
3    False
4    False
Name: 학년, dtype: bool

In [16]:
## => 석차 컬럼 <= 10
dataDF[dataDF.columns[-1]] <= 10

0     True
1     True
2    False
3     True
4    False
Name:  석차, dtype: bool

In [18]:
## ==> 학년은 1학년이면서 석차가 10위 안에 있는 학생 즉, and 연산, &
maskSR = (dataDF[dataDF.columns[1]] == 1) & (dataDF[dataDF.columns[-1]] <= 10)
maskSR

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [19]:
dataDF[maskSR]

    이름  학년  반   석차
0  홍길동   1  1    8
1  고길동   1  3    1