###
============================================================
						PANDAS 실습 문제
										2026년 05월 01일
============================================================
[사용 파일]
- 시도별 전출입 인구수.xlsx

In [7]:
# ============================================================
# 문제 1) 데이터 파일을 읽고 기본 구조를 확인하세요.
# [요구사항]
# 1.  "시도별 전출입 인구수.xlsx" 파일의 "데이터" 시트를 읽어 DataFrame으로 저장하세요.
# 2. 앞부분 5개 행을 출력하세요.
# 3. 데이터의 행수와 열수를 출력하세요.
# 4. 각 컬럼의 자료형을 확인하세요.
# ============================================================

import pandas as pd
df = pd.read_excel(r'C:\Users\KDT-008\Desktop\KDT_14\[2]PANDAS\DATA\시도별 전출입 인구수.xlsx')

df.head()

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전출지별,전입지별,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182

In [9]:
print(df.shape[0])
print(df.shape[1])

325
50

In [10]:
print(df.dtypes)

전출지별    object
전입지별    object
1970    object
1971    object
1972    object
1973    object
1974    object
1975    object
1976    object
1977    object
1978    object
1979    object
1980    object
1981    object
1982    object
1983    object
1984    object
1985    object
1986    object
1987    object
1988    object
1989    object
1990    object
1991    object
1992    object
1993    object
1994    object
1995    object
1996    object
1997    object
1998    object
1999    object
2000    object
2001    object
2002    object
2003    object
2004    object
2005    object
2006    object
2007    object
2008    object
2009    object
2010    object
2011    object
2012    object
2013    object
2014    object
2015    object
2016    object
2017    object
dtype: object

In [ ]:
### 데이터 전처리 진행 체크
# 1. 전출지별 컬럼 -> 이전 값으로 채우면 결측치 처리
# 2. 0번행 -> 의미없는 행이므로 삭제
# 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object -> 이유 : '-' 문제

In [11]:
# ============================================================
# 문제 2) 불필요한 행을 삭제하고 인덱스를 초기화하세요.
# [요구사항]
# 1. 데이터 파일을 읽은 후, 두 번째 행에 들어 있는 "이동자수 (명)" 설명 행을 삭제하세요.
# 2. 삭제 후 행 인덱스를 0부터 다시 설정하세요.
# 3. 처리 전과 처리 후의 행과 열 수를 각각 출력하세요.
# 4. 처리 후 앞부분 5개 행을 출력하세요.
# # ============================================================

ndf = df.drop(index=0)
ndf = ndf.reset_index(drop=True)
print(f"처리 전 행의 개수 :{df.shape[0]}, 처리 전 열의 개수 :{df.shape[1]}")
print(f"처리 후 행의 개수 :{ndf.shape[0]}, 처리 후 열의 개수 :{ndf.shape[1]}")

처리 전 행의 개수 :325, 처리 전 열의 개수 :50
처리 후 행의 개수 :324, 처리 후 열의 개수 :50

In [12]:
ndf.head()

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
1,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
2,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
3,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182
4,NaN,인천광역시,-,-,-,-,-,-,-,-,...,565585,478169,462051,499567,468666,461613,452297,473223,441646,409465

In [3]:
# ============================================================
# 문제 3) 연도 컬럼의 자료형을 숫자형으로 변환하세요.
# [요구사항]
# 1. 1970년부터 2017년까지의 연도 컬럼을 선택하세요.
# 2. 연도별 이동자수 데이터에 포함된 "-" 값을 결측치로 처리할 수 있도록 변환하세요.
# 4. 변환 후 연도 컬럼들의 자료형을 출력하세요.
# 5. 전체 결측치 개수를 출력하세요.
# ============================================================
import numpy as np

year = ndf.loc['1970' : '2017']
year = year.replace('-', np.nan)
print(year)
print(year.dtypes)
print(year.isnull().sum().sum())

     전출지별   전입지별      1970      1971      1972      1973      1974      1975  \
198  충청북도     전국  147916.0  156593.0  124530.0  156909.0  166708.0  324499.0
199   NaN  서울특별시   37625.0   39139.0   29513.0   36260.0   40154.0   72525.0
200   NaN  부산광역시    3840.0    3073.0    2424.0    3353.0    4763.0    7790.0
201   NaN  대구광역시       NaN       NaN       NaN       NaN       NaN       NaN

         1976      1977  ...    2008    2009    2010    2011    2012    2013  \
198  213011.0  220085.0  ...  237759  230351  229707  220515  207622  212860
199   50313.0   50472.0  ...   15672   15612   14561   13753   13624   13209
200    6885.0    7178.0  ...    1548    1556    1618    1628    1489    1565
201       NaN       NaN  ...    1607    1613    1655    1555    1705    1693

       2014    2015    2016    2017
198  213577  213188  197668  194915
199   13291   13197   13032   12961
200    1932    1757    1559    1660
201    1816    1450    1517    1443

[4 rows x 50 columns]
전출지별     object
전입지별     object
1970    float64
1971    float64
1972    float64
1973    float64
1974    float64
1975    float64
1976    float64
1977    float64
1978    float64
1979    float64
1980    float64
1981      int64
1982      int64
1983      int64
1984      int64
1985      int64
1986      int64
1987      int64
1988      int64
1989      int64
1990      int64
1991      int64
1992      int64
1993      int64
1994      int64
1995      int64
1996      int64
1997      int64
1998      int64
1999      int64
2000      int64
2001      int64
2002      int64
2003      int64
2004      int64
2005      int64
2006      int64
2007      int64
2008      int64
2009      int64
2010      int64
2011      int64
2012      int64
2013      int64
2014      int64
2015      int64
2016      int64
2017      int64
dtype: object
14

C:\Users\KDT-008\AppData\Local\Temp\ipykernel_20420\3128822666.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  year = year.replace('-', np.nan)

In [4]:
# ============================================================
# 문제 4) 특정 행과 열을 선택하세요.
# [요구사항]
# 1. 전출지별, 전입지별, 1970, 1980, 1990, 2000, 2010, 2017 컬럼만 선택하여 새로운 DataFrame을 만드세요.
# 2. 앞에서 10개 행만 출력하세요.
# 3. 전출지별, 전입지별, 2017 컬럼만 출력하세요.
# 4. 0번 행의 2017년 이동자수 값을 선택하여 출력하세요.
# # ============================================================

ndf1 = ndf[['전출지별', '전입지별', '1970', '1980', '1990', '2000', '2010', '2017']]
print(ndf1.head(10))

  전출지별     전입지별     1970     1980     1990     2000     2010     2017
0   전국       전국  4046536  8258573  9459209  9009441  8226594  7154226
1  NaN    서울특별시  1742813  2767816  2726492  2219407  1733015  1472937
2  NaN    부산광역시   448577   904252   761684   595975   519334   439073
3  NaN    대구광역시        -        -   526547   477595   370817   321182
4  NaN    인천광역시        -        -   567863   531318   462051   409465
5  NaN    광주광역시        -        -   330810   301498   268574   208138
6  NaN    대전광역시        -        -   296756   312560   262432   211449
7  NaN    울산광역시        -        -        -   166690   161146   135199
8  NaN  세종특별자치시        -        -        -        -        -    82073
9  NaN      경기도   452060  1085764  1609933  2042327  2168820  1888324

In [5]:
# ============================================================
# 문제 5) 서울특별시에서 다른 지역으로 전출한 데이터만 추출하세요.
# ============================================================

seoul = ndf.iloc[1]
print(seoul)

전출지별        NaN
전입지별      서울특별시
1970    1742813
1971    1671705
1972    1349333
1973    1831858
1974    2050392
1975    3396662
1976    2756510
1977    2893403
1978    3307439
1979    2589667
1980    2767816
1981    2859860
1982    2997854
1983    3434184
1984    3052558
1985    2784387
1986    2683013
1987    2853398
1988    3388387
1989    3049117
1990    2726492
1991    2437238
1992    2395814
1993    2259333
1994    2240086
1995    2165332
1996    2159555
1997    2074884
1998    1802931
1999    2337989
2000    2219407
2001    2295784
2002    2318051
2003    2242723
2004    1926235
2005    1990749
2006    2173907
2007    2078045
2008    2025358
2009    1873188
2010    1733015
2011    1721748
2012    1555281
2013    1520090
2014    1573594
2015    1589431
2016    1515602
2017    1472937
Name: 1, dtype: object

In [ ]:
# ============================================================
# 문제 6)  서울특별시로 전입한  지역의 데이터 추출한 문제입니다
# [요구사항]
# 1. 전입지별이  "부산광역시", "대구광역시", "인천광역시", "경기도"  중 하나인 행만 추출하세요.
# 2. 전입지별, 1990, 2000, 2010, 2017 컬럼만 출력하세요.
# 3. 2017년 이동자수 기준으로 내림차순 정렬하세요.
# ============================================================

mask = ndf.isin(["부산광역시", "대구광역시", "인천광역시", "경기도"])
ndf1 = ndf[[ '전입지별', '1970', '1980', '1990', '2000', '2010', '2017']]
print(ndf1)

      전출지별   전입지별   1970   1971   1972   1973   1974   1975   1976   1977  \
0    False  False  False  False  False  False  False  False  False  False
1    False  False  False  False  False  False  False  False  False  False
2    False   True  False  False  False  False  False  False  False  False
3    False   True  False  False  False  False  False  False  False  False
4    False   True  False  False  False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
319  False  False  False  False  False  False  False  False  False  False
320  False  False  False  False  False  False  False  False  False  False
321  False  False  False  False  False  False  False  False  False  False
322  False  False  False  False  False  False  False  False  False  False
323  False  False  False  False  False  False  False  False  False  False

     ...   2008   2009   2010   2011   2012   2013   2014   2015   2016   2017
0    ...  False  False  False  False  False  False  False  False  False  False
1    ...  False  False  False  False  False  False  False  False  False  False
2    ...  False  False  False  False  False  False  False  False  False  False
3    ...  False  False  False  False  False  False  False  False  False  False
4    ...  False  False  False  False  False  False  False  False  False  False
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
319  ...  False  False  False  False  False  False  False  False  False  False
320  ...  False  False  False  False  False  False  False  False  False  False
321  ...  False  False  False  False  False  False  False  False  False  False
322  ...  False  False  False  False  False  False  False  False  False  False
323  ...  False  False  False  False  False  False  False  False  False  False

[324 rows x 50 columns]

In [ ]:
# ============================================================
# 문제 7) query()를 사용하여 2017년 이동자수가 100000명 이상인 데이터를 추출하세요.

# [요구사항]
# 1. 연도 컬럼을 숫자형으로 변환한 DataFrame을 사용하세요.
# 2. query()를 사용하여 2017년 이동자수가 100000명 이상인 행을 추출하세요.
# 3. 전출지별, 전입지별, 2017 컬럼만 출력하세요.
# 4. 2017년 이동자수 기준으로 내림차순 정렬하세요.

# [주의사항]
# - 컬럼명이 숫자 형태이면 query()에서 사용하기 어려울 수 있습니다.
# - 필요한 경우 2017 컬럼명을 "Y2017"과 같이 변경한 후 query()를 사용하세요.
# ============================================================

In [ ]:
# ============================================================
# 문제 8) 인덱스를 설정하고 정렬하세요.

# [요구사항]
# 1. 전출지별과 전입지별 컬럼을 행 인덱스로 설정하세요.
# 2. 설정된 인덱스를 기준으로 오름차순 정렬하세요.
# 3. loc을 사용하여 전출지별이 "서울특별시"인 데이터만 선택하세요.
# 4. 선택 결과에서 2017년 이동자수 상위 5개 지역을 출력하세요.

# ============================================================

In [ ]:
# ============================================================
# 문제 9) 기초 통계 값을 확인하세요.

# [요구사항]
# 1. 1970년부터 2017년까지 연도 컬럼만 선택하세요.
# 2. 각 연도별 이동자수 평균값을 구하세요.
# 3. 각 연도별 이동자수 최댓값을 구하세요.
# 4. 2017년 이동자수의 평균, 중앙값, 최댓값, 최솟값, 표준편차를 각각 출력하세요.
# 5. describe()를 사용하여 전체 연도 컬럼의 기술 통계 정보를 출력하세요.
# ============================================================

In [ ]:
# ============================================================
# 문제 10) 행/열을 추가하고 값을 수정하세요.

# [요구사항]
# 1. 전출지별이 "서울특별시"인 데이터만 추출한 후 복사본을 만드세요.
# 2. 2017년 이동자수에서 2010년 이동자수를 뺀 값을 "증감_2010_2017" 컬럼으로 추가하세요.
# 3. "증감_2010_2017" 값이 양수이면 "증가", 0이면 "동일", 음수이면 "감소"로 표시하는 "변화구분" 컬럼을 추가하세요.
# 4. 전입지별이 "서울특별시"인 행의 변화구분 값을 "자기지역"으로 수정하세요.
# 5. 전입지별, 2010, 2017, 증감_2010_2017, 변화구분 컬럼만 출력하세요.
# ============================================================