### 【 PANDAS 실습 문제 】

- 날짜: 2026년 05월 01일
- 사용 파일: 시도별 전출입 인구수.xlsx

#### 준비 0) 모듈 및 데이터 설정

In [84]:
## 모듈 로딩
import pandas as pd

In [85]:
## 데이터 준비
DATA_FILE = '../../DATA/시도별 전출입 인구수.xlsx'

---
#### 문제 1) 데이터 파일을 읽고 기본 구조를 확인하세요.
[요구사항]
1. "시도별 전출입 인구수.xlsx" 파일의 "데이터" 시트를 읽어 DataFrame으로 저장하세요.
2. 앞부분 5개 행을 출력하세요.
3. 데이터의 행수와 열수를 출력하세요.
4. 각 컬럼의 자료형을 확인하세요.
---

In [86]:
## xlsx ==> DataFrame으로 로딩
df = pd.read_excel(DATA_FILE, sheet_name="데이터")

In [87]:
## 2. 앞부분 5개 행을 출력하세요.
print("[앞부분 5개 행]")
df.head()

[앞부분 5개 행]

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전출지별,전입지별,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182

In [88]:
## 3. 데이터의 행수와 열수를 출력하세요.
print(f"[행/열 개수]  {df.shape}")
print(f"행 : {df.shape[0]}개")
print(f"열 : {df.shape[1]}개")

[행/열 개수]  (325, 50)
행 : 325개
열 : 50개

In [89]:
## 4.각 컬럼의 자료형을 확인하세요.
print(f"[컬럼별 자료형]")
df.dtypes

[컬럼별 자료형]

전출지별    object
전입지별    object
1970    object
1971    object
1972    object
1973    object
1974    object
1975    object
1976    object
1977    object
1978    object
1979    object
1980    object
1981    object
1982    object
1983    object
1984    object
1985    object
1986    object
1987    object
1988    object
1989    object
1990    object
1991    object
1992    object
1993    object
1994    object
1995    object
1996    object
1997    object
1998    object
1999    object
2000    object
2001    object
2002    object
2003    object
2004    object
2005    object
2006    object
2007    object
2008    object
2009    object
2010    object
2011    object
2012    object
2013    object
2014    object
2015    object
2016    object
2017    object
dtype: object

In [90]:
### 데이터 전처리 진행 체크
# 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
# 2. 0번행 의미 없는 행 => 삭제
# 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제

---
#### 문제 2) 불필요한 행을 삭제하고 인덱스를 초기화하세요
[요구사항]
1. 데이터 파일을 읽은 후, 두 번째 행에 들어 있는 "이동자수 (명)" 설명 행을 삭제하세요.
2. 삭제 후 reset_index()를 사용하여 행 인덱스를 0부터 다시 설정하세요.
3. 처리 전과 처리 후의 shape를 각각 출력하세요.
4. 처리 후 앞부분 5개 행을 출력하세요.
---

In [91]:
## 1. 데이터 파일을 읽은 후, 두 번째 행에 들어 있는 "이동자수 (명)" 설명 행을 삭제하세요.
df2 = df.drop(index=0)
df2.head(3)

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073

In [92]:
##2. 삭제 후 reset_index()를 사용하여 행 인덱스를 0부터 다시 설정하세요.
df2 = df2.reset_index(drop=True)

In [93]:
##3. 처리 전과 처리 후의 shape를 각각 출력하세요.
print("[처리 전 shape]", df.shape, "===>", "[처리 후 shape]", df2.shape)

[처리 전 shape] (325, 50) ===> [처리 후 shape] (324, 50)

In [94]:
## 4. 처리 후 앞부분 5개 행을 출력하세요.
df2.head(3)

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
1,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
2,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073

---
#### 문제 3) 연도 컬럼의 자료형을 숫자형으로 변환하세요.
[요구사항]
1. 1970년부터 2017년까지의 연도 컬럼을 선택하세요.
2. 연도별 이동자수 데이터에 포함된 "-" 값을 결측치로 처리할 수 있도록 변환하세요.
4. 변환 후 연도 컬럼들의 자료형을 출력하세요.
5. 전체 결측치 개수를 출력하세요.
---

In [95]:
## 1. 1970년부터 2017년까지의 연도 컬럼을 선택하세요.
year_cols = df2.columns[2:]
year_cols

Index(['1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978',
       '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017'],
      dtype='object')

In [96]:
## 특정 컬럼 선택 후 기본 정보 확인
yearDF = df2[ year_cols ]
display( yearDF.head(3) )
yearDF.info()

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,8410276,7324380,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
1,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,3307439,2589667,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
2,448577,389797,362202,482061,680984,805979,724664,785117,895337,809483,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 48 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1970    324 non-null    object
 1   1971    324 non-null    object
 2   1972    324 non-null    object
 3   1973    324 non-null    object
 4   1974    324 non-null    object
 5   1975    324 non-null    object
 6   1976    324 non-null    object
 7   1977    324 non-null    object
 8   1978    324 non-null    object
 9   1979    324 non-null    object
 10  1980    324 non-null    object
 11  1981    324 non-null    object
 12  1982    324 non-null    object
 13  1983    324 non-null    object
 14  1984    324 non-null    object
 15  1985    324 non-null    object
 16  1986    324 non-null    object
 17  1987    324 non-null    object
 18  1988    324 non-null    object
 19  1989    324 non-null    object
 20  1990    324 non-null    object
 21  1991    324 non-null    object
 22  1992    324 non-null    object
 23  1993    324 non-null    object
 24  1994    324 non-null    object
 25  1995    324 non-null    object
 26  1996    324 non-null    object
 27  1997    324 non-null    object
 28  1998    324 non-null    object
 29  1999    324 non-null    object
 30  2000    324 non-null    object
 31  2001    324 non-null    object
 32  2002    324 non-null    object
 33  2003    324 non-null    object
 34  2004    324 non-null    object
 35  2005    324 non-null    object
 36  2006    324 non-null    object
 37  2007    324 non-null    object
 38  2008    324 non-null    object
 39  2009    324 non-null    object
 40  2010    324 non-null    object
 41  2011    324 non-null    object
 42  2012    324 non-null    object
 43  2013    324 non-null    object
 44  2014    324 non-null    object
 45  2015    324 non-null    object
 46  2016    324 non-null    object
 47  2017    324 non-null    object
dtypes: object(48)
memory usage: 121.6+ KB

In [97]:
## 2. 연도별 이동자수 데이터에 포함된 "-" 값을 특정값으로 변경하기
## -------------------------------------------------------------------------
## FutureWarning : 현재 코드는 실행되지만 앞으로 Pandas 버전 변경 시 변경 경고
## -------------------------------------------------------------------------
# C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_31568\3585299255.py:2: FutureWarning: 
# Downcasting behavior in `replace` is deprecated and will be removed in a future version. 
# To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. 
# To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
#   yearDF.replace("-", 0).astype('int')
# "-"를 0으로 바꾸는 과정 => Pandas가 내부적으로 자료형을 자동 추론
#                         여기서 자동 다운캐스팅 방식이 앞으로 바뀔 예정
# [해결]
# 가장 깔끔한 해결은 replace 후 명시적으로 infer_objects()를 호출
## -------------------------------------------------------------------------
yearDF = yearDF.replace("-", 0).infer_objects(copy=False).astype("int")

C:\Users\KDT-008\AppData\Local\Temp\ipykernel_8716\915129241.py:15: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  yearDF = yearDF.replace("-", 0).infer_objects(copy=False).astype("int")

In [98]:
## [권장] 둘 다 조건에 따라 값을 바꾸는 Pandas 메서드
## => mask(조건, 변경값) : 조건이 True인 경우 값 변경 
yearDF = yearDF.mask(yearDF == "-", 0)

## => where(조건, 변경값) : 조건이 True인 값은 그대로 두고, False인 값 변경
yearDF = yearDF.where(yearDF != "-", 0).astype("int")

In [99]:
## 2. 연도별 이동자수 데이터에 포함된 "-" 값을 결측치로 처리할 수 있도록 변환하세요.
import numpy as np
yearDF = yearDF.replace("-",np.nan)

In [100]:
## 3. 변환 후 연도 컬럼들의 자료형을 출력하세요.
yearDF.dtypes.head()

1970    int64
1971    int64
1972    int64
1973    int64
1974    int64
dtype: object

In [101]:
## 4. 전체 결측치 개수를 출력하세요.
#print(f"[년도별 결측치 개수]\n{yearDF.isna().sum()}")
print(f"[전  체 결측치 개수]  {yearDF.isna().sum().sum()}개")

[전  체 결측치 개수]  0개

---
#### 문제 4) 특정 행과 열을 선택하세요.
[요구사항]
1. 전출지별, 전입지별, 1970, 1980, 1990, 2000, 2010, 2017 컬럼만 선택하여 새로운 DataFrame을 만드세요.
2. 앞에서 10개 행만 출력하세요.
3. 전출지별, 전입지별, 2017 컬럼만 출력하세요.
4. 0번 행의 2017년 이동자수 값을 선택하여 출력하세요.
---

In [102]:
## 1. 전출지별, 전입지별, 1970, 1980, 1990, 2000, 2010, 2017 컬럼만 선택하여 새로운 DataFrame을 만드세요.
select_cols = ["전출지별", "전입지별", "1970", "1980", "1990", "2000", "2010", "2017"]
partDF = df2[select_cols]
partDF.head(3)

  전출지별   전입지별     1970     1980     1990     2000     2010     2017
0   전국     전국  4046536  8258573  9459209  9009441  8226594  7154226
1  NaN  서울특별시  1742813  2767816  2726492  2219407  1733015  1472937
2  NaN  부산광역시   448577   904252   761684   595975   519334   439073

In [103]:
## 2. 앞에서 10개 행만 출력하세요.
print("[앞에서 10개 행]")
display(partDF.iloc[:10])

[앞에서 10개 행]

  전출지별     전입지별     1970     1980     1990     2000     2010     2017
0   전국       전국  4046536  8258573  9459209  9009441  8226594  7154226
1  NaN    서울특별시  1742813  2767816  2726492  2219407  1733015  1472937
2  NaN    부산광역시   448577   904252   761684   595975   519334   439073
3  NaN    대구광역시        -        -   526547   477595   370817   321182
4  NaN    인천광역시        -        -   567863   531318   462051   409465
5  NaN    광주광역시        -        -   330810   301498   268574   208138
6  NaN    대전광역시        -        -   296756   312560   262432   211449
7  NaN    울산광역시        -        -        -   166690   161146   135199
8  NaN  세종특별자치시        -        -        -        -        -    82073
9  NaN      경기도   452060  1085764  1609933  2042327  2168820  1888324

In [104]:
## 3. 전출지별, 전입지별, 2017 컬럼만 출력하세요.
print("[전출지별, 전입지별, 2017 컬럼]")
display(partDF.loc[:, ["전출지별", "전입지별", "2017"]].head())
display( partDF[["전출지별", "전입지별", "2017"]].head() )

[전출지별, 전입지별, 2017 컬럼]

  전출지별   전입지별     2017
0   전국     전국  7154226
1  NaN  서울특별시  1472937
2  NaN  부산광역시   439073
3  NaN  대구광역시   321182
4  NaN  인천광역시   409465

  전출지별   전입지별     2017
0   전국     전국  7154226
1  NaN  서울특별시  1472937
2  NaN  부산광역시   439073
3  NaN  대구광역시   321182
4  NaN  인천광역시   409465

In [105]:
## 4. 0번 행의 2017년 이동자수 값을 선택하여 출력하세요.
print(f"[0번 행의 2017년 이동자수] { partDF.loc[0, '2017']:,}명")

[0번 행의 2017년 이동자수] 7,154,226명

---
#### 문제 5) 서울특별시에서 다른 지역으로 전출한 데이터만 추출하세요.
* 서울특별시 ---> 다른 지역 이동
* 전출지별 : 서울특별시,  전입지별 : 서울특별시가 아닌 지역명
---

In [106]:
## 전출지별 : 서울특벌시 ==> 전입지별 : 다른 지역 
## 전출지별의 NAN값 채우기
seoulDF = df2.copy()
seoulDF["전출지별"] = seoulDF["전출지별"].ffill()
seoulDF.tail(10)

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
314,제주특별자치도,세종특별자치시,-,-,-,-,-,-,-,-,...,-,-,-,-,58,74,134,188,210,255
315,제주특별자치도,경기도,727,817,420,641,702,1811,1351,1516,...,5223,5046,5022,4990,4655,4775,5291,5845,6520,6931
316,제주특별자치도,강원도,435,191,150,184,194,728,295,306,...,570,582,542,516,520,511,543,607,694,693
317,제주특별자치도,충청북도,42,59,116,82,115,185,205,128,...,519,475,478,518,484,433,546,621,726,754
318,제주특별자치도,충청남도,294,155,238,235,285,554,493,535,...,731,756,774,776,696,676,757,896,834,967
319,제주특별자치도,전라북도,139,202,141,210,219,415,392,408,...,668,579,672,561,551,516,609,683,733,768
320,제주특별자치도,전라남도,631,965,857,952,1133,2808,2608,2652,...,1143,1123,1002,1026,966,1001,928,1062,1127,1102
321,제주특별자치도,경상북도,374,619,468,576,625,1123,1141,1004,...,761,704,738,756,699,781,728,903,931,994
322,제주특별자치도,경상남도,474,479,440,571,1208,1517,863,1122,...,1517,1474,1324,1367,1227,1278,1223,1500,1448,1501
323,제주특별자치도,제주특별자치도,9290,12427,12210,16158,19580,34221,23291,31028,...,59564,55673,55507,59846,54280,60607,59673,59036,66444,63275

In [107]:
## 전출지별 : 서울특벌시 ==> 전입지별 : 다른 지역 
## 전출지별의 NAN값 채우기
#seoulDF[ seoulDF["전출지별"]=="서울특별시" ].head(2)
boolSR = seoulDF["전출지별"]=="서울특별시" 
seoulDF = seoulDF[boolSR]
seoulDF.shape, seoulDF.columns

((18, 50),
 Index(['전출지별', '전입지별', '1970', '1971', '1972', '1973', '1974', '1975', '1976',
        '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985',
        '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994',
        '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
        '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012',
        '2013', '2014', '2015', '2016', '2017'],
       dtype='object'))

In [108]:
## 전출지별 컬럼 동일값으로 삭제
seoulDF = seoulDF.drop(columns='전출지별')
seoulDF.shape

(18, 49)

In [109]:
## 전입지별이 서울특별시, 전국이 아닌 행 선택
seoulDF[ (seoulDF['전입지별'] != '전국') & (seoulDF['전입지별'] != '서울특별시') ]

,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
20,부산광역시,11568,11130,11768,16307,22220,27515,23732,27213,29856,...,17353,17738,17418,18816,16135,16153,17320,17009,15062,14484
21,대구광역시,-,-,-,-,-,-,-,-,-,...,9720,10464,10277,10397,10135,10631,10062,10191,9623,8891
22,인천광역시,-,-,-,-,-,-,-,-,-,...,50493,45392,46082,51641,49640,47424,43212,44915,43745,40485
23,광주광역시,-,-,-,-,-,-,-,-,-,...,10846,11725,11095,10587,10154,9129,9759,9216,8354,7932
24,대전광역시,-,-,-,-,-,-,-,-,-,...,13515,13632,13819,13900,14080,13440,13403,13453,12619,11815
25,울산광역시,-,-,-,-,-,-,-,-,-,...,5057,4845,4742,5188,5691,5542,6047,5950,5102,4260
26,세종특별자치시,-,-,-,-,-,-,-,-,-,...,-,-,-,-,2998,2851,6481,7550,5943,5813
27,경기도,130149,150313,93333,143234,149045,253705,202276,207722,237684,...,412408,398282,410735,373771,354135,340801,332785,359337,370760,342433
28,강원도,9352,12885,13561,16481,15479,27837,25927,25415,26700,...,23668,23331,22736,23624,22332,20601,21173,22659,21590,21016
29,충청북도,6700,9457,10853,12617,11786,21073,18029,17478,18420,...,15294,15295,15461,15318,14555,13783,14244,14379,14087,13302
30,충청남도,15954,18943,23406,27139,25509,51205,41447,43993,48091,...,27458,24889,24522,24723,22269,21486,21473,22299,21741,21020
31,전라북도,10814,13192,16583,18642,16647,34411,29835,28444,29676,...,18390,18332,17569,17755,16120,14909,14566,14835,13835,13179
32,전라남도,10513,16755,20157,22160,21314,46610,46251,43430,44624,...,16601,17468,16429,15974,14765,14187,14591,14598,13065,12426
33,경상북도,11868,16459,22073,27531,26902,46177,40376,41155,42940,...,15425,16569,16042,15818,15191,14420,14456,15113,14236,12464
34,경상남도,8409,10001,11263,15193,16771,23150,22400,27393,28697,...,15438,15303,15689,16039,14474,14447,14799,15220,13717,12692
35,제주특별자치도,1039,1325,1617,2456,2261,3440,3623,3551,3937,...,5473,5332,5714,6133,6954,7828,9031,10434,10465,10404

In [110]:
## 전입지별이 서울특별시, 전국이 아닌 행 선택
seoulDF[~ seoulDF["전입지별"].isin(["서울특별시", "전국"]) ]

,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
20,부산광역시,11568,11130,11768,16307,22220,27515,23732,27213,29856,...,17353,17738,17418,18816,16135,16153,17320,17009,15062,14484
21,대구광역시,-,-,-,-,-,-,-,-,-,...,9720,10464,10277,10397,10135,10631,10062,10191,9623,8891
22,인천광역시,-,-,-,-,-,-,-,-,-,...,50493,45392,46082,51641,49640,47424,43212,44915,43745,40485
23,광주광역시,-,-,-,-,-,-,-,-,-,...,10846,11725,11095,10587,10154,9129,9759,9216,8354,7932
24,대전광역시,-,-,-,-,-,-,-,-,-,...,13515,13632,13819,13900,14080,13440,13403,13453,12619,11815
25,울산광역시,-,-,-,-,-,-,-,-,-,...,5057,4845,4742,5188,5691,5542,6047,5950,5102,4260
26,세종특별자치시,-,-,-,-,-,-,-,-,-,...,-,-,-,-,2998,2851,6481,7550,5943,5813
27,경기도,130149,150313,93333,143234,149045,253705,202276,207722,237684,...,412408,398282,410735,373771,354135,340801,332785,359337,370760,342433
28,강원도,9352,12885,13561,16481,15479,27837,25927,25415,26700,...,23668,23331,22736,23624,22332,20601,21173,22659,21590,21016
29,충청북도,6700,9457,10853,12617,11786,21073,18029,17478,18420,...,15294,15295,15461,15318,14555,13783,14244,14379,14087,13302
30,충청남도,15954,18943,23406,27139,25509,51205,41447,43993,48091,...,27458,24889,24522,24723,22269,21486,21473,22299,21741,21020
31,전라북도,10814,13192,16583,18642,16647,34411,29835,28444,29676,...,18390,18332,17569,17755,16120,14909,14566,14835,13835,13179
32,전라남도,10513,16755,20157,22160,21314,46610,46251,43430,44624,...,16601,17468,16429,15974,14765,14187,14591,14598,13065,12426
33,경상북도,11868,16459,22073,27531,26902,46177,40376,41155,42940,...,15425,16569,16042,15818,15191,14420,14456,15113,14236,12464
34,경상남도,8409,10001,11263,15193,16771,23150,22400,27393,28697,...,15438,15303,15689,16039,14474,14447,14799,15220,13717,12692
35,제주특별자치도,1039,1325,1617,2456,2261,3440,3623,3551,3937,...,5473,5332,5714,6133,6954,7828,9031,10434,10465,10404

In [111]:
## 전입지별이 서울특별시, 전국이 아닌 행 선택
seoulDF.query('전입지별!="서울특별시" & 전입지별 !="전국"').reset_index(drop=True)

,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,부산광역시,11568,11130,11768,16307,22220,27515,23732,27213,29856,...,17353,17738,17418,18816,16135,16153,17320,17009,15062,14484
1,대구광역시,-,-,-,-,-,-,-,-,-,...,9720,10464,10277,10397,10135,10631,10062,10191,9623,8891
2,인천광역시,-,-,-,-,-,-,-,-,-,...,50493,45392,46082,51641,49640,47424,43212,44915,43745,40485
3,광주광역시,-,-,-,-,-,-,-,-,-,...,10846,11725,11095,10587,10154,9129,9759,9216,8354,7932
4,대전광역시,-,-,-,-,-,-,-,-,-,...,13515,13632,13819,13900,14080,13440,13403,13453,12619,11815
5,울산광역시,-,-,-,-,-,-,-,-,-,...,5057,4845,4742,5188,5691,5542,6047,5950,5102,4260
6,세종특별자치시,-,-,-,-,-,-,-,-,-,...,-,-,-,-,2998,2851,6481,7550,5943,5813
7,경기도,130149,150313,93333,143234,149045,253705,202276,207722,237684,...,412408,398282,410735,373771,354135,340801,332785,359337,370760,342433
8,강원도,9352,12885,13561,16481,15479,27837,25927,25415,26700,...,23668,23331,22736,23624,22332,20601,21173,22659,21590,21016
9,충청북도,6700,9457,10853,12617,11786,21073,18029,17478,18420,...,15294,15295,15461,15318,14555,13783,14244,14379,14087,13302
10,충청남도,15954,18943,23406,27139,25509,51205,41447,43993,48091,...,27458,24889,24522,24723,22269,21486,21473,22299,21741,21020
11,전라북도,10814,13192,16583,18642,16647,34411,29835,28444,29676,...,18390,18332,17569,17755,16120,14909,14566,14835,13835,13179
12,전라남도,10513,16755,20157,22160,21314,46610,46251,43430,44624,...,16601,17468,16429,15974,14765,14187,14591,14598,13065,12426
13,경상북도,11868,16459,22073,27531,26902,46177,40376,41155,42940,...,15425,16569,16042,15818,15191,14420,14456,15113,14236,12464
14,경상남도,8409,10001,11263,15193,16771,23150,22400,27393,28697,...,15438,15303,15689,16039,14474,14447,14799,15220,13717,12692
15,제주특별자치도,1039,1325,1617,2456,2261,3440,3623,3551,3937,...,5473,5332,5714,6133,6954,7828,9031,10434,10465,10404

---
#### 문제 6) 서울특별시로 전입한 지역의 데이터 추출한 문제입니다

[요구사항]
1. 전출지별이  "부산광역시", "대구광역시", "인천광역시", "경기도"  중 하나인 행만 추출하세요.
2. 전입지별, 1990, 2000, 2010, 2017 컬럼만 출력하세요.
3. 2017년 이동자수 기준으로 내림차순 정렬하세요.
---

In [112]:
## 필요 데이터 준비
inSeourDF = df2.copy()
inSeourDF['전출지별'] = inSeourDF['전출지별'].ffill()
inSeourDF.head()

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
1,전국,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
2,전국,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
3,전국,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182
4,전국,인천광역시,-,-,-,-,-,-,-,-,...,565585,478169,462051,499567,468666,461613,452297,473223,441646,409465

In [113]:
## ===========================================
## SettingWithCopyWarning 경고
## ===========================================
# C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_33412\2741080109.py:5: SettingWithCopyWarning: 
# A value is trying to be set on a copy of a slice from a DataFrame

# See the caveats in the documentation: 
# https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
# View 
# - 메모리 낭비를 줄이기 위해 원본 데이터를 복사하지 않고 일부를 바라보는 방식
# - 하지만 View를 수정하면 원본도 영향을 받을 수 있음
# =============================================
# [원인]
# => 원본 DataFrame에서 일부 행/열을 추출해서 만든 DataFrame에 값을 수정/삭제하려고 할 때 발생
#    inplace=True로 원본에 적용할 경우 
# => 이 DataFrame이 원본의 일부인지 복사본인지 불명확
# => 수정한 내용이 원본에 반영될 수도 있고 안 될 수도 있음!!!
# [해결]
# => 일부 데이터를 추출한 뒤 별도로 작업할 목적이면 .copy()로 독립적인 DF로 작업
# ===============================================

In [114]:
## 전입지가 서울특별시인 행 추출
mask = inSeourDF['전입지별'] == '서울특별시'
inSeoulDF = inSeourDF[mask]

inSeoulDF.drop(columns='전입지별', inplace=True)
inSeoulDF.shape

C:\Users\KDT-008\AppData\Local\Temp\ipykernel_8716\2741080109.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inSeoulDF.drop(columns='전입지별', inplace=True)

(18, 49)

In [115]:
## 전출지가 "부산광역시", "대구광역시", "인천광역시", "경기도"
mask = inSeoulDF["전출지별"].isin(["부산광역시", "대구광역시", "인천광역시", "경기도"])
inSeoulDF = inSeoulDF[mask]
inSeoulDF

,전출지별,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
37,부산광역시,24263,30144,18260,24251,30284,59914,43416,42685,48142,...,25249,24459,23116,23016,21437,19621,20616,19441,19236,19460
55,대구광역시,-,-,-,-,-,-,-,-,-,...,14824,15469,13915,13310,13838,13673,13735,13038,12802,13011
73,인천광역시,-,-,-,-,-,-,-,-,-,...,40479,38858,35670,33008,32216,33017,34380,33570,32486,32528
163,경기도,95388,95423,90470,107177,107518,207641,144524,154021,164771,...,323515,317952,285963,272407,254175,246464,249701,239557,234357,234448

In [116]:
## 전출지별, 1990, 2000, 2010, 2017 컬럼
inSeoulDF = inSeoulDF[[ "전출지별", "1990", "2000", "2010", "2017"]]
inSeoulDF

      전출지별    1990    2000    2010    2017
37   부산광역시   34978   28564   23116   19460
55   대구광역시   19521   16970   13915   13011
73   인천광역시   43247   45970   35670   32528
163    경기도  282914  312616  285963  234448

In [117]:
## 2017년도 기준으로 정렬
inSeoulDF.sort_values(by="2000", ascending=False)

      전출지별    1990    2000    2010    2017
163    경기도  282914  312616  285963  234448
73   인천광역시   43247   45970   35670   32528
37   부산광역시   34978   28564   23116   19460
55   대구광역시   19521   16970   13915   13011

---
#### 문제 7) query()를 사용하여 2017년 이동자수가 100000명 이상인 데이터를 추출하세요.

[요구사항]
1. 연도 컬럼을 숫자형으로 변환한 DataFrame을 사용하세요.
2. query()를 사용하여 2017년 이동자수가 100000명 이상인 행을 추출하세요.
3. 전출지별, 전입지별, 2017 컬럼만 출력하세요.
4. 2017년 이동자수 기준으로 내림차순 정렬하세요.

[주의사항]
- 컬럼명이 숫자 형태이면 query()에서 사용하기 어려울 수 있습니다.
- 필요한 경우 2017 컬럼명을 "Y2017"과 같이 변경한 후 query()를 사용하세요.
---

In [118]:
## 작업을 위한 복사 DF
partDF = df2.copy()

## 전출지별의 결측치 채우기
partDF['전출지별'] = partDF['전출지별'].ffill()

In [119]:
## 1. 연도 컬럼을 숫자형으로 변환한 DataFrame을 사용하세요.
partDF[partDF.columns[2:]] = partDF[partDF.columns[2:]].replace("-", 0).astype("int")

C:\Users\KDT-008\AppData\Local\Temp\ipykernel_8716\3932316575.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  partDF[partDF.columns[2:]] = partDF[partDF.columns[2:]].replace("-", 0).astype("int")

In [120]:
partDF[partDF.columns[2:]] = partDF[partDF.columns[2:]].mask(partDF[partDF.columns[2:]] == "-", 0).astype(int)

In [121]:
partDF.dtypes.head(3)

전출지별    object
전입지별    object
1970     int64
dtype: object

In [122]:
## 2. query()를 사용하여 2017년 이동자수가 100000명 이상인 행을 추출하세요.
## 2-1: 불린인덱싱
partDF[ partDF['2017'] >= 1000000 ].sort_index(axis=1, ascending=False)

,전출지별,전입지별,2017,2016,2015,2014,2013,2012,2011,2010,...,1979,1978,1977,1976,1975,1974,1973,1972,1971,1970
0,전국,전국,7154226,7378430,7755286,7629098,7411784,7506691,8127195,8226594,...,7324380,8410276,7397623,6773250,9011440,5297969,4860418,3687938,4210164,4046536
1,전국,서울특별시,1472937,1515602,1589431,1573594,1520090,1555281,1721748,1733015,...,2589667,3307439,2893403,2756510,3396662,2050392,1831858,1349333,1671705,1742813
9,전국,경기도,1888324,1958593,1993080,1891775,1895434,1944962,2062422,2168820,...,984187,985879,880019,770036,1006818,579194,542224,418045,533375,452060
18,서울특별시,전국,1571423,1655859,1726687,1661425,1620640,1658928,1834806,1848038,...,2441242,3028911,2678007,2495620,2937093,1819660,1647268,1210559,1419016,1448985
19,서울특별시,서울특별시,1018807,1061915,1129529,1098023,1053008,1069300,1215122,1199708,...,1883742,2518286,2212213,2041724,2401970,1511726,1345508,985945,1158556,1232619
162,경기도,전국,1772162,1824976,1898312,1834379,1821303,1862209,1986623,2026383,...,786271,817561,753564,645942,825258,484597,454426,382945,412098,353535
171,경기도,경기도,1259187,1301101,1346264,1275072,1274495,1294565,1387806,1435269,...,496327,529175,492040,395632,493101,309489,284129,235877,263045,212365

In [123]:
## 2-2. query()메서드
## -> query()에서 숫자 컬럼명을 바로 쓰기 어렵기 때문에 2017 컬럼명을 변경
#partDF = partDF.rename(columns={'2017': "Y2017"})

partDF = partDF.rename( columns={str(year): "Y" + str(year) for year in range(1970, 2018)} )
print(partDF.shape, partDF.columns, sep='\n')

partDF = partDF.query("Y2017 >= 100000")
partDF.shape

(324, 50)
Index(['전출지별', '전입지별', 'Y1970', 'Y1971', 'Y1972', 'Y1973', 'Y1974', 'Y1975',
       'Y1976', 'Y1977', 'Y1978', 'Y1979', 'Y1980', 'Y1981', 'Y1982', 'Y1983',
       'Y1984', 'Y1985', 'Y1986', 'Y1987', 'Y1988', 'Y1989', 'Y1990', 'Y1991',
       'Y1992', 'Y1993', 'Y1994', 'Y1995', 'Y1996', 'Y1997', 'Y1998', 'Y1999',
       'Y2000', 'Y2001', 'Y2002', 'Y2003', 'Y2004', 'Y2005', 'Y2006', 'Y2007',
       'Y2008', 'Y2009', 'Y2010', 'Y2011', 'Y2012', 'Y2013', 'Y2014', 'Y2015',
       'Y2016', 'Y2017'],
      dtype='object')

(48, 50)

In [124]:
## 3. 전출지별, 전입지별, 2017 컬럼만 출력하세요.
partDF = partDF[['전출지별','전입지별', 'Y2017']]
partDF.head()

  전출지별   전입지별    Y2017
0   전국     전국  7154226
1   전국  서울특별시  1472937
2   전국  부산광역시   439073
3   전국  대구광역시   321182
4   전국  인천광역시   409465

In [125]:
## 4. 2017년 이동자수 기준으로 내림차순 정렬하세요.
partDF = partDF.sort_values(by="Y2017", ascending=False).reset_index(drop=True)
partDF.head(3)

  전출지별 전입지별    Y2017
0   전국   전국  7154226
1   전국  경기도  1888324
2  경기도   전국  1772162

---
#### 문제 8) 인덱스를 설정하고 정렬하세요.

[요구사항]
1. 전출지별과 전입지별 컬럼을 행 인덱스로 설정하세요.
2. 설정된 인덱스를 기준으로 오름차순 정렬하세요.
3. loc을 사용하여 전출지별이 "서울특별시"인 데이터만 선택하세요.
4. 선택 결과에서 2017년 이동자수 상위 5개 지역을 출력하세요.

---

In [126]:
# 데이터 준비
dataDF = df2.copy()

# 전출지별 결측치 채우기
dataDF['전출지별'] = dataDF['전출지별'].ffill()

In [127]:
# 1. 전출지별과 전입지별 컬럼을 행 인덱스로 설정하세요.    => 멀티 인덱스
dataDF2 = dataDF.set_index( keys=['전출지별','전입지별'] )
dataDF2.index

MultiIndex([(     '전국',      '전국'),
            (     '전국',   '서울특별시'),
            (     '전국',   '부산광역시'),
            (     '전국',   '대구광역시'),
            (     '전국',   '인천광역시'),
            (     '전국',   '광주광역시'),
            (     '전국',   '대전광역시'),
            (     '전국',   '울산광역시'),
            (     '전국', '세종특별자치시'),
            (     '전국',     '경기도'),
            ...
            ('제주특별자치도', '세종특별자치시'),
            ('제주특별자치도',     '경기도'),
            ('제주특별자치도',     '강원도'),
            ('제주특별자치도',    '충청북도'),
            ('제주특별자치도',    '충청남도'),
            ('제주특별자치도',    '전라북도'),
            ('제주특별자치도',    '전라남도'),
            ('제주특별자치도',    '경상북도'),
            ('제주특별자치도',    '경상남도'),
            ('제주특별자치도', '제주특별자치도')],
           names=['전출지별', '전입지별'], length=324)

In [128]:
# 2. 설정된 인덱스를 기준으로 오름차순 정렬하세요.
dataDF2 = dataDF2.sort_index()
dataDF2.index

MultiIndex([( '강원도',     '강원도'),
            ( '강원도',     '경기도'),
            ( '강원도',    '경상남도'),
            ( '강원도',    '경상북도'),
            ( '강원도',   '광주광역시'),
            ( '강원도',   '대구광역시'),
            ( '강원도',   '대전광역시'),
            ( '강원도',   '부산광역시'),
            ( '강원도',   '서울특별시'),
            ( '강원도', '세종특별자치시'),
            ...
            ('충청북도',   '서울특별시'),
            ('충청북도', '세종특별자치시'),
            ('충청북도',   '울산광역시'),
            ('충청북도',   '인천광역시'),
            ('충청북도',      '전국'),
            ('충청북도',    '전라남도'),
            ('충청북도',    '전라북도'),
            ('충청북도', '제주특별자치도'),
            ('충청북도',    '충청남도'),
            ('충청북도',    '충청북도')],
           names=['전출지별', '전입지별'], length=324)

In [129]:
# 3. loc을 사용하여 전출지별이 "서울특별시"인 데이터만 선택하세요.
#    멀티인덱스에서 level=0이 서울특별시
seoulDF = dataDF2.loc['서울특별시']

In [130]:
# 4. 선택 결과에서 2017년 이동자수 상위 5개 지역을 출력하세요.
#    2017컬럼의 값을 기준으로 정렬
top5 = seoulDF.sort_values(by='2017', ascending=False).head(5)
display(top5[['2017']])

          2017
전입지별
전국     1571423
서울특별시  1018807
경기도     342433
인천광역시    40485
충청남도     21020

---
#### 문제 9) 기초 통계 값을 확인하세요.
[요구사항]
1. 1970년부터 2017년까지 연도 컬럼만 선택하세요.
2. 각 연도별 이동자수 평균값을 구하세요.
3. 각 연도별 이동자수 최댓값을 구하세요.
4. 2017년 이동자수의 평균, 중앙값, 최댓값, 최솟값, 표준편차를 각각 출력하세요.
5. describe()를 사용하여 전체 연도 컬럼의 기술 통계 정보를 출력하세요.
---

In [49]:
# 데이터 준비
dataDF = df2.copy()

# 전출지별 결측치 채우기
dataDF['전출지별'] = dataDF['전출지별'].ffill()

In [56]:
# 1. 1970년부터 2017년까지 연도 컬럼만 선택하세요.
## 특정 컬럼 선택 후 기본 정보 확인
yearDF = dataDF[ dataDF.columns[2:] ]

## 컬럼에 '-' 처리
yearDF = yearDF.mask(yearDF =='-', 0).astype(int)

## 기본 정보
yearDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 0 to 323
Data columns (total 48 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1970    324 non-null    int64
 1   1971    324 non-null    int64
 2   1972    324 non-null    int64
 3   1973    324 non-null    int64
 4   1974    324 non-null    int64
 5   1975    324 non-null    int64
 6   1976    324 non-null    int64
 7   1977    324 non-null    int64
 8   1978    324 non-null    int64
 9   1979    324 non-null    int64
 10  1980    324 non-null    int64
 11  1981    324 non-null    int64
 12  1982    324 non-null    int64
 13  1983    324 non-null    int64
 14  1984    324 non-null    int64
 15  1985    324 non-null    int64
 16  1986    324 non-null    int64
 17  1987    324 non-null    int64
 18  1988    324 non-null    int64
 19  1989    324 non-null    int64
 20  1990    324 non-null    int64
 21  1991    324 non-null    int64
 22  1992    324 non-null    int64
 23  1993    324 non-null    int64
 24  1994    324 non-null    int64
 25  1995    324 non-null    int64
 26  1996    324 non-null    int64
 27  1997    324 non-null    int64
 28  1998    324 non-null    int64
 29  1999    324 non-null    int64
 30  2000    324 non-null    int64
 31  2001    324 non-null    int64
 32  2002    324 non-null    int64
 33  2003    324 non-null    int64
 34  2004    324 non-null    int64
 35  2005    324 non-null    int64
 36  2006    324 non-null    int64
 37  2007    324 non-null    int64
 38  2008    324 non-null    int64
 39  2009    324 non-null    int64
 40  2010    324 non-null    int64
 41  2011    324 non-null    int64
 42  2012    324 non-null    int64
 43  2013    324 non-null    int64
 44  2014    324 non-null    int64
 45  2015    324 non-null    int64
 46  2016    324 non-null    int64
 47  2017    324 non-null    int64
dtypes: int64(48)
memory usage: 121.6 KB

In [57]:
# 2. 각 연도별 이동자수 평균값을 구하세요.
print("[각 연도별 평균값]")
display(yearDF.mean())

[각 연도별 평균값]

1970     49939.080247
1971     51977.333333
1972     45530.098765
1973     59807.611111
1974     64992.259259
1975    110922.246914
1976     83502.666667
1977     91296.358025
1978    103312.117284
1979     90334.839506
1980    101870.351852
1981    101062.111111
1982    106326.839506
1983    120756.716049
1984    111571.981481
1985    107093.290123
1986    106864.580247
1987    114922.839506
1988    123074.320988
1989    115015.049383
1990    116780.358025
1991    110874.580247
1992    111500.938272
1993    108729.111111
1994    108539.679012
1995    112013.197531
1996    109320.654321
1997    108887.765432
1998    100695.283951
1999    116485.765432
2000    111227.666667
2001    114690.728395
2002    118326.679012
2003    117488.950617
2004    105775.246914
2005    108585.148148
2006    115334.246914
2007    111976.567901
2008    108743.901235
2009    104781.172840
2010    101562.888889
2011    100335.740741
2012     92675.197531
2013     91503.506173
2014     94186.395062
2015     95744.271605
2016     91091.728395
2017     88323.777778
dtype: float64

In [58]:
# 3. 각 연도별 이동자수 최댓값을 구하세요.
print("[각 연도별 최댓값]")
display(yearDF.max())

[각 연도별 최댓값]

1970    4046536
1971    4210164
1972    3687938
1973    4860418
1974    5297969
1975    9011440
1976    6773250
1977    7397623
1978    8410276
1979    7324380
1980    8258573
1981    8194516
1982    8616474
1983    9795811
1984    9043238
1985    8679097
1986    8660428
1987    9308750
1988    9969020
1989    9316219
1990    9459209
1991    8980841
1992    9031576
1993    8807058
1994    8791714
1995    9073069
1996    8854973
1997    8819909
1998    8156318
1999    9435347
2000    9009441
2001    9289949
2002    9584461
2003    9516605
2004    8567795
2005    8795397
2006    9342074
2007    9070102
2008    8808256
2009    8487275
2010    8226594
2011    8127195
2012    7506691
2013    7411784
2014    7629098
2015    7755286
2016    7378430
2017    7154226
dtype: int64

In [60]:
# 4. 2017년 이동자수의 평균, 중앙값, 최댓값, 최솟값, 표준편차를 각각 출력하세요.
print("[2017년 통계]")
print("평   균 :", yearDF['2017'].mean())
print("중 앙 값 :", yearDF['2017'].median())
print("최 댓 값 :", yearDF['2017'].max())
print("최 솟 값 :", yearDF['2017'].min())
print("표준편차 :", yearDF['2017'].std())

[2017년 통계]
평   균 : 88323.77777777778
중 앙 값 : 3782.5
최 댓 값 : 7154226
최 솟 값 : 119
표준편차 : 450749.90422768745

In [61]:
# 5. describe()를 사용하여 전체 연도 컬럼의 기술 통계 정보를 출력하세요.
display(yearDF.describe())

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
count,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,...,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02
mean,4.993908e+04,5.197733e+04,4.553010e+04,5.980761e+04,6.499226e+04,1.109222e+05,8.350267e+04,9.129636e+04,1.033121e+05,9.033484e+04,...,1.087439e+05,1.047812e+05,1.015629e+05,1.003357e+05,9.267520e+04,9.150351e+04,9.418640e+04,9.574427e+04,9.109173e+04,8.832378e+04
std,2.735617e+05,2.798395e+05,2.435924e+05,3.220157e+05,3.528406e+05,5.951653e+05,4.560874e+05,4.963381e+05,5.638369e+05,4.821911e+05,...,5.570235e+05,5.362021e+05,5.195057e+05,5.123145e+05,4.727953e+05,4.661929e+05,4.784523e+05,4.882273e+05,4.654667e+05,4.507499e+05
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.900000e+01,4.100000e+01,6.300000e+01,1.160000e+02,1.050000e+02,1.190000e+02
25%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.223250e+03,1.117250e+03,1.145000e+03,1.108000e+03,1.454500e+03,1.453750e+03,1.530000e+03,1.543250e+03,1.470000e+03,1.479500e+03
50%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,3.860000e+03,3.894500e+03,3.849000e+03,3.922000e+03,3.969500e+03,3.767000e+03,3.927000e+03,3.929000e+03,3.746000e+03,3.782500e+03
75%,5.720000e+03,5.995750e+03,5.135000e+03,6.457250e+03,7.642000e+03,1.393550e+04,1.010125e+04,1.028875e+04,1.228700e+04,1.133400e+04,...,2.002800e+04,1.947425e+04,1.891350e+04,1.817525e+04,1.751400e+04,1.635200e+04,1.706375e+04,1.696100e+04,1.644425e+04,1.621075e+04
max,4.046536e+06,4.210164e+06,3.687938e+06,4.860418e+06,5.297969e+06,9.011440e+06,6.773250e+06,7.397623e+06,8.410276e+06,7.324380e+06,...,8.808256e+06,8.487275e+06,8.226594e+06,8.127195e+06,7.506691e+06,7.411784e+06,7.629098e+06,7.755286e+06,7.378430e+06,7.154226e+06

---
### 문제 10) 행/열을 추가하고 값을 수정하세요.

[요구사항]
1. 전출지별이 "서울특별시"인 데이터만 추출한 후 복사본을 만드세요.
2. 2017년 이동자수에서 2010년 이동자수를 뺀 값을 "증감_2010_2017" 컬럼으로 추가하세요.
3. "증감_2010_2017" 값이 양수이면 "증가", 0이면 "동일", 음수이면 "감소"로 표시하는 "변화구분" 컬럼을 추가하세요.
4. 전입지별이 "서울특별시"인 행의 변화구분 값을 "자기지역"으로 수정하세요.
5. 전입지별, 2010, 2017, 증감_2010_2017, 변화구분 컬럼만 출력하세요.
---

In [66]:
# 데이터 준비
dataDF = df2.copy()

# 전출지별 결측치 채우기
dataDF['전출지별'] = dataDF['전출지별'].ffill()

# 1997 ~ 2017 '-' 처리
dataDF[dataDF.columns[2:]]= dataDF[dataDF.columns[2:]].mask(dataDF == '-', 0).astype(int)

dataDF.dtypes

전출지별    object
전입지별    object
1970     int64
1971     int64
1972     int64
1973     int64
1974     int64
1975     int64
1976     int64
1977     int64
1978     int64
1979     int64
1980     int64
1981     int64
1982     int64
1983     int64
1984     int64
1985     int64
1986     int64
1987     int64
1988     int64
1989     int64
1990     int64
1991     int64
1992     int64
1993     int64
1994     int64
1995     int64
1996     int64
1997     int64
1998     int64
1999     int64
2000     int64
2001     int64
2002     int64
2003     int64
2004     int64
2005     int64
2006     int64
2007     int64
2008     int64
2009     int64
2010     int64
2011     int64
2012     int64
2013     int64
2014     int64
2015     int64
2016     int64
2017     int64
dtype: object

In [69]:
# 1. 전출지별이 "서울특별시"인 데이터만 추출한 후 복사본을 만드세요.
seoulDF = dataDF[ dataDF['전출지별'] == '서울특별시' ].copy()

In [70]:

# 2. 2017년 이동자수에서 2010년 이동자수를 뺀 값을 "증감_2010_2017" 컬럼으로 추가하세요.
seoulDF["증감_2010_2017"] = seoulDF['2017'] - seoulDF['2010']
seoulDF.head(2)

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,증감_2010_2017
18,서울특별시,전국,1448985,1419016,1210559,1647268,1819660,2937093,2495620,2678007,...,1925452,1848038,1834806,1658928,1620640,1661425,1726687,1655859,1571423,-276615
19,서울특별시,서울특별시,1232619,1158556,985945,1345508,1511726,2401970,2041724,2212213,...,1286855,1199708,1215122,1069300,1053008,1098023,1129529,1061915,1018807,-180901

In [74]:
# 3. "증감_2010_2017" 값이 양수이면 "증가", 0이면 "동일", 음수이면 "감소"로 표시하는 "변화구분" 컬럼을 추가하세요.

# seoulDF["변화구분"] = np.where(
#     seoulDF["증감_2010_2017"] > 0, "증가",
#     np.where(seoulDF["증감_2010_2017"] == 0, "동일", "감소")
# )

seoulDF["변화구분"] = "동일"
seoulDF["변화구분"] = seoulDF["변화구분"].mask( seoulDF["증감_2010_2017"] > 0,  "증가" )
seoulDF["변화구분"] = seoulDF["변화구분"].mask(seoulDF["증감_2010_2017"] < 0,  "감소" )

In [75]:
# 4. 전입지별이 "서울특별시"인 행의 변화구분 값을 "자기지역"으로 수정하세요.
seoulDF.loc[seoulDF["전입지별"] == "서울특별시", "변화구분"] = "자기지역"

In [76]:
# 5. 전입지별, 2010, 2017, 증감_2010_2017, 변화구분 컬럼만 출력하세요.
result = seoulDF[["전입지별", "2010", "2017", "증감_2010_2017", "변화구분"]]
display(result)

       전입지별     2010     2017  증감_2010_2017  변화구분
18       전국  1848038  1571423       -276615    감소
19    서울특별시  1199708  1018807       -180901  자기지역
20    부산광역시    17418    14484         -2934    감소
21    대구광역시    10277     8891         -1386    감소
22    인천광역시    46082    40485         -5597    감소
23    광주광역시    11095     7932         -3163    감소
24    대전광역시    13819    11815         -2004    감소
25    울산광역시     4742     4260          -482    감소
26  세종특별자치시        0     5813          5813    증가
27      경기도   410735   342433        -68302    감소
28      강원도    22736    21016         -1720    감소
29     충청북도    15461    13302         -2159    감소
30     충청남도    24522    21020         -3502    감소
31     전라북도    17569    13179         -4390    감소
32     전라남도    16429    12426         -4003    감소
33     경상북도    16042    12464         -3578    감소
34     경상남도    15689    12692         -2997    감소
35  제주특별자치도     5714    10404          4690    증가