### 【 PANDAS 실습 문제 】

- 날짜: 2026년 05월 01일
- 사용 파일: 시도별 전출입 인구수.xlsx

[1] 모듈 및 데이터 설정 <hr>

In [1]:
## 모듈 로딩
import pandas as pd

In [2]:
## 데이터 준비
DATA_FILE = '../DATA/시도별 전출입 인구수.xlsx'

[2] 데이터 로딩 <hr>

In [3]:
## xlsx ==> DataFrame으로 로딩
df = pd.read_excel(DATA_FILE, sheet_name="데이터")

In [4]:
## 앞부분 5개 행을 출력하세요.
print("[앞부분 5개 행]")
df.head()

[앞부분 5개 행]

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전출지별,전입지별,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182

In [5]:
## 데이터의 행수와 열수를 출력하세요.
print(f"[행/열 개수]  {df.shape}")
print(f"행 : {df.shape[0]}개, 열 : {df.shape[1]}개")

[행/열 개수]  (325, 50)
행 : 325개, 열 : 50개

In [6]:
## 각 컬럼의 자료형을 확인하세요.
print(f"[컬럼별 자료형]")
df.dtypes

[컬럼별 자료형]

전출지별    object
전입지별    object
1970    object
1971    object
1972    object
1973    object
1974    object
1975    object
1976    object
1977    object
1978    object
1979    object
1980    object
1981    object
1982    object
1983    object
1984    object
1985    object
1986    object
1987    object
1988    object
1989    object
1990    object
1991    object
1992    object
1993    object
1994    object
1995    object
1996    object
1997    object
1998    object
1999    object
2000    object
2001    object
2002    object
2003    object
2004    object
2005    object
2006    object
2007    object
2008    object
2009    object
2010    object
2011    object
2012    object
2013    object
2014    object
2015    object
2016    object
2017    object
dtype: object

In [7]:
## -------------------------------------------------------------
## 데이터 전처리 진행 체크 
## -------------------------------------------------------------
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
## 2. 0번행 의미 없는 행 => 삭제
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
## -------------------------------------------------------------

[3] 기본 전처리<hr>

In [8]:
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
df['전출지별'] = df['전출지별'].ffill()

In [9]:
## 2. 0번행 의미 없는 행 => 삭제
df.drop(index=0, inplace=True)

In [10]:
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
df = df.mask(df=='-', 0)
df[df.columns[2:]] = df[df.columns[2:]].astype(int)
df.dtypes

전출지별    object
전입지별    object
1970     int64
1971     int64
1972     int64
1973     int64
1974     int64
1975     int64
1976     int64
1977     int64
1978     int64
1979     int64
1980     int64
1981     int64
1982     int64
1983     int64
1984     int64
1985     int64
1986     int64
1987     int64
1988     int64
1989     int64
1990     int64
1991     int64
1992     int64
1993     int64
1994     int64
1995     int64
1996     int64
1997     int64
1998     int64
1999     int64
2000     int64
2001     int64
2002     int64
2003     int64
2004     int64
2005     int64
2006     int64
2007     int64
2008     int64
2009     int64
2010     int64
2011     int64
2012     int64
2013     int64
2014     int64
2015     int64
2016     int64
2017     int64
dtype: object

---
#### 문제 9) 기초 통계 값을 확인하세요.
[요구사항]
1. 1970년부터 2017년까지 연도 컬럼만 선택하세요.
2. 각 연도별 이동자수 평균값을 구하세요.
3. 각 연도별 이동자수 최댓값을 구하세요.
4. 2017년 이동자수의 평균, 중앙값, 최댓값, 최솟값, 표준편차를 각각 출력하세요.
5. describe()를 사용하여 전체 연도 컬럼의 기술 통계 정보를 출력하세요.
---

In [11]:
# 1. 1970년부터 2017년까지 연도 컬럼만 선택하세요.
## 특정 컬럼 선택 후 기본 정보 확인
yearDF = df[ df.columns[2:] ]

## 컬럼에 '-' 처리
yearDF = yearDF.mask(yearDF =='-', 0).astype(int)

## 기본 정보
yearDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 324 entries, 1 to 324
Data columns (total 48 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1970    324 non-null    int64
 1   1971    324 non-null    int64
 2   1972    324 non-null    int64
 3   1973    324 non-null    int64
 4   1974    324 non-null    int64
 5   1975    324 non-null    int64
 6   1976    324 non-null    int64
 7   1977    324 non-null    int64
 8   1978    324 non-null    int64
 9   1979    324 non-null    int64
 10  1980    324 non-null    int64
 11  1981    324 non-null    int64
 12  1982    324 non-null    int64
 13  1983    324 non-null    int64
 14  1984    324 non-null    int64
 15  1985    324 non-null    int64
 16  1986    324 non-null    int64
 17  1987    324 non-null    int64
 18  1988    324 non-null    int64
 19  1989    324 non-null    int64
 20  1990    324 non-null    int64
 21  1991    324 non-null    int64
 22  1992    324 non-null    int64
 23  1993    324 non-null    int64
 24  1994    324 non-null    int64
 25  1995    324 non-null    int64
 26  1996    324 non-null    int64
 27  1997    324 non-null    int64
 28  1998    324 non-null    int64
 29  1999    324 non-null    int64
 30  2000    324 non-null    int64
 31  2001    324 non-null    int64
 32  2002    324 non-null    int64
 33  2003    324 non-null    int64
 34  2004    324 non-null    int64
 35  2005    324 non-null    int64
 36  2006    324 non-null    int64
 37  2007    324 non-null    int64
 38  2008    324 non-null    int64
 39  2009    324 non-null    int64
 40  2010    324 non-null    int64
 41  2011    324 non-null    int64
 42  2012    324 non-null    int64
 43  2013    324 non-null    int64
 44  2014    324 non-null    int64
 45  2015    324 non-null    int64
 46  2016    324 non-null    int64
 47  2017    324 non-null    int64
dtypes: int64(48)
memory usage: 121.6 KB

In [12]:
# 2. 각 연도별 이동자수 평균값을 구하세요.
print("[각 연도별 평균값]")
display(yearDF.mean())

[각 연도별 평균값]

1970     49939.080247
1971     51977.333333
1972     45530.098765
1973     59807.611111
1974     64992.259259
1975    110922.246914
1976     83502.666667
1977     91296.358025
1978    103312.117284
1979     90334.839506
1980    101870.351852
1981    101062.111111
1982    106326.839506
1983    120756.716049
1984    111571.981481
1985    107093.290123
1986    106864.580247
1987    114922.839506
1988    123074.320988
1989    115015.049383
1990    116780.358025
1991    110874.580247
1992    111500.938272
1993    108729.111111
1994    108539.679012
1995    112013.197531
1996    109320.654321
1997    108887.765432
1998    100695.283951
1999    116485.765432
2000    111227.666667
2001    114690.728395
2002    118326.679012
2003    117488.950617
2004    105775.246914
2005    108585.148148
2006    115334.246914
2007    111976.567901
2008    108743.901235
2009    104781.172840
2010    101562.888889
2011    100335.740741
2012     92675.197531
2013     91503.506173
2014     94186.395062
2015     95744.271605
2016     91091.728395
2017     88323.777778
dtype: float64

In [13]:
# 3. 각 연도별 이동자수 최댓값을 구하세요.
print("[각 연도별 최댓값]")
display(yearDF.max())

[각 연도별 최댓값]

1970    4046536
1971    4210164
1972    3687938
1973    4860418
1974    5297969
1975    9011440
1976    6773250
1977    7397623
1978    8410276
1979    7324380
1980    8258573
1981    8194516
1982    8616474
1983    9795811
1984    9043238
1985    8679097
1986    8660428
1987    9308750
1988    9969020
1989    9316219
1990    9459209
1991    8980841
1992    9031576
1993    8807058
1994    8791714
1995    9073069
1996    8854973
1997    8819909
1998    8156318
1999    9435347
2000    9009441
2001    9289949
2002    9584461
2003    9516605
2004    8567795
2005    8795397
2006    9342074
2007    9070102
2008    8808256
2009    8487275
2010    8226594
2011    8127195
2012    7506691
2013    7411784
2014    7629098
2015    7755286
2016    7378430
2017    7154226
dtype: int64

In [14]:
# 4. 2017년 이동자수의 평균, 중앙값, 최댓값, 최솟값, 표준편차를 각각 출력하세요.
print("[2017년 통계]")
print("평   균 :", yearDF['2017'].mean())
print("중 앙 값 :", yearDF['2017'].median())
print("최 댓 값 :", yearDF['2017'].max())
print("최 솟 값 :", yearDF['2017'].min())
print("표준편차 :", yearDF['2017'].std())

[2017년 통계]
평   균 : 88323.77777777778
중 앙 값 : 3782.5
최 댓 값 : 7154226
최 솟 값 : 119
표준편차 : 450749.90422768745

In [15]:
# 5. describe()를 사용하여 전체 연도 컬럼의 기술 통계 정보를 출력하세요.
display(yearDF.describe())

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
count,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,...,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02,3.240000e+02
mean,4.993908e+04,5.197733e+04,4.553010e+04,5.980761e+04,6.499226e+04,1.109222e+05,8.350267e+04,9.129636e+04,1.033121e+05,9.033484e+04,...,1.087439e+05,1.047812e+05,1.015629e+05,1.003357e+05,9.267520e+04,9.150351e+04,9.418640e+04,9.574427e+04,9.109173e+04,8.832378e+04
std,2.735617e+05,2.798395e+05,2.435924e+05,3.220157e+05,3.528406e+05,5.951653e+05,4.560874e+05,4.963381e+05,5.638369e+05,4.821911e+05,...,5.570235e+05,5.362021e+05,5.195057e+05,5.123145e+05,4.727953e+05,4.661929e+05,4.784523e+05,4.882273e+05,4.654667e+05,4.507499e+05
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.900000e+01,4.100000e+01,6.300000e+01,1.160000e+02,1.050000e+02,1.190000e+02
25%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.223250e+03,1.117250e+03,1.145000e+03,1.108000e+03,1.454500e+03,1.453750e+03,1.530000e+03,1.543250e+03,1.470000e+03,1.479500e+03
50%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,3.860000e+03,3.894500e+03,3.849000e+03,3.922000e+03,3.969500e+03,3.767000e+03,3.927000e+03,3.929000e+03,3.746000e+03,3.782500e+03
75%,5.720000e+03,5.995750e+03,5.135000e+03,6.457250e+03,7.642000e+03,1.393550e+04,1.010125e+04,1.028875e+04,1.228700e+04,1.133400e+04,...,2.002800e+04,1.947425e+04,1.891350e+04,1.817525e+04,1.751400e+04,1.635200e+04,1.706375e+04,1.696100e+04,1.644425e+04,1.621075e+04
max,4.046536e+06,4.210164e+06,3.687938e+06,4.860418e+06,5.297969e+06,9.011440e+06,6.773250e+06,7.397623e+06,8.410276e+06,7.324380e+06,...,8.808256e+06,8.487275e+06,8.226594e+06,8.127195e+06,7.506691e+06,7.411784e+06,7.629098e+06,7.755286e+06,7.378430e+06,7.154226e+06