### 【 PANDAS 실습 문제 】

- 날짜: 2026년 05월 01일
- 사용 파일: 시도별 전출입 인구수.xlsx

[1] 모듈 및 데이터 설정 <hr>

In [1]:
## 모듈 로딩
import pandas as pd

In [2]:
## 데이터 준비
DATA_FILE = '../DATA/시도별 전출입 인구수.xlsx'

[2] 데이터 로딩 <hr>

In [3]:
## xlsx ==> DataFrame으로 로딩
df = pd.read_excel(DATA_FILE, sheet_name="데이터")

In [4]:
## 앞부분 5개 행을 출력하세요.
print("[앞부분 5개 행]")
df.head()

[앞부분 5개 행]

,전출지별,전입지별,1970,1971,1972,1973,1974,1975,1976,1977,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,전출지별,전입지별,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),...,이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명),이동자수 (명)
1,전국,전국,4046536,4210164,3687938,4860418,5297969,9011440,6773250,7397623,...,8808256,8487275,8226594,8127195,7506691,7411784,7629098,7755286,7378430,7154226
2,NaN,서울특별시,1742813,1671705,1349333,1831858,2050392,3396662,2756510,2893403,...,2025358,1873188,1733015,1721748,1555281,1520090,1573594,1589431,1515602,1472937
3,NaN,부산광역시,448577,389797,362202,482061,680984,805979,724664,785117,...,514502,519310,519334,508043,461042,478451,485710,507031,459015,439073
4,NaN,대구광역시,-,-,-,-,-,-,-,-,...,409938,398626,370817,370563,348642,351873,350213,351424,328228,321182

In [5]:
## 데이터의 행수와 열수를 출력하세요.
print(f"[행/열 개수]  {df.shape}")
print(f"행 : {df.shape[0]}개, 열 : {df.shape[1]}개")

[행/열 개수]  (325, 50)
행 : 325개, 열 : 50개

In [6]:
## 각 컬럼의 자료형을 확인하세요.
print(f"[컬럼별 자료형]")
df.dtypes

[컬럼별 자료형]

전출지별    object
전입지별    object
1970    object
1971    object
1972    object
1973    object
1974    object
1975    object
1976    object
1977    object
1978    object
1979    object
1980    object
1981    object
1982    object
1983    object
1984    object
1985    object
1986    object
1987    object
1988    object
1989    object
1990    object
1991    object
1992    object
1993    object
1994    object
1995    object
1996    object
1997    object
1998    object
1999    object
2000    object
2001    object
2002    object
2003    object
2004    object
2005    object
2006    object
2007    object
2008    object
2009    object
2010    object
2011    object
2012    object
2013    object
2014    object
2015    object
2016    object
2017    object
dtype: object

In [7]:
## -------------------------------------------------------------
## 데이터 전처리 진행 체크 
## -------------------------------------------------------------
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
## 2. 0번행 의미 없는 행 => 삭제
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
## -------------------------------------------------------------

[3] 기본 전처리<hr>

In [8]:
## 1. 전출지별 컬럼 => 이전값으로 채우면 결측치 처리
df['전출지별'] = df['전출지별'].ffill()

In [9]:
## 2. 0번행 의미 없는 행 => 삭제
df.drop(index=0, inplace=True)

In [10]:
## 3. 1970년 컬럼 ~ 2017년 컬럼 타입 object => '-' 문제
df = df.mask(df=='-', 0)
df[df.columns[2:]] = df[df.columns[2:]].astype(int)
df.dtypes

전출지별    object
전입지별    object
1970     int64
1971     int64
1972     int64
1973     int64
1974     int64
1975     int64
1976     int64
1977     int64
1978     int64
1979     int64
1980     int64
1981     int64
1982     int64
1983     int64
1984     int64
1985     int64
1986     int64
1987     int64
1988     int64
1989     int64
1990     int64
1991     int64
1992     int64
1993     int64
1994     int64
1995     int64
1996     int64
1997     int64
1998     int64
1999     int64
2000     int64
2001     int64
2002     int64
2003     int64
2004     int64
2005     int64
2006     int64
2007     int64
2008     int64
2009     int64
2010     int64
2011     int64
2012     int64
2013     int64
2014     int64
2015     int64
2016     int64
2017     int64
dtype: object

---
#### 문제 8) 인덱스를 설정하고 정렬하세요.

[요구사항]
1. 전출지별과 전입지별 컬럼을 행 인덱스로 설정하세요.
2. 설정된 인덱스를 기준으로 오름차순 정렬하세요.
3. loc을 사용하여 전출지별이 "서울특별시"인 데이터만 선택하세요.
4. 선택 결과에서 2017년 이동자수 상위 5개 지역을 출력하세요.
---

In [11]:
# 1. 전출지별과 전입지별 컬럼을 행 인덱스로 설정하세요.
dataDF2 = df.set_index( keys=['전출지별','전입지별'] )
dataDF2.index

MultiIndex([(     '전국',      '전국'),
            (     '전국',   '서울특별시'),
            (     '전국',   '부산광역시'),
            (     '전국',   '대구광역시'),
            (     '전국',   '인천광역시'),
            (     '전국',   '광주광역시'),
            (     '전국',   '대전광역시'),
            (     '전국',   '울산광역시'),
            (     '전국', '세종특별자치시'),
            (     '전국',     '경기도'),
            ...
            ('제주특별자치도', '세종특별자치시'),
            ('제주특별자치도',     '경기도'),
            ('제주특별자치도',     '강원도'),
            ('제주특별자치도',    '충청북도'),
            ('제주특별자치도',    '충청남도'),
            ('제주특별자치도',    '전라북도'),
            ('제주특별자치도',    '전라남도'),
            ('제주특별자치도',    '경상북도'),
            ('제주특별자치도',    '경상남도'),
            ('제주특별자치도', '제주특별자치도')],
           names=['전출지별', '전입지별'], length=324)

In [12]:
# 2. 설정된 인덱스를 기준으로 오름차순 정렬하세요.
dataDF2 = dataDF2.sort_index()
dataDF2.index

MultiIndex([( '강원도',     '강원도'),
            ( '강원도',     '경기도'),
            ( '강원도',    '경상남도'),
            ( '강원도',    '경상북도'),
            ( '강원도',   '광주광역시'),
            ( '강원도',   '대구광역시'),
            ( '강원도',   '대전광역시'),
            ( '강원도',   '부산광역시'),
            ( '강원도',   '서울특별시'),
            ( '강원도', '세종특별자치시'),
            ...
            ('충청북도',   '서울특별시'),
            ('충청북도', '세종특별자치시'),
            ('충청북도',   '울산광역시'),
            ('충청북도',   '인천광역시'),
            ('충청북도',      '전국'),
            ('충청북도',    '전라남도'),
            ('충청북도',    '전라북도'),
            ('충청북도', '제주특별자치도'),
            ('충청북도',    '충청남도'),
            ('충청북도',    '충청북도')],
           names=['전출지별', '전입지별'], length=324)

In [13]:
# 3. loc을 사용하여 전출지별이 "서울특별시"인 데이터만 선택하세요.
#    멀티인덱스에서 level=0이 서울특별시
seoulDF = dataDF2.loc['서울특별시']

In [14]:
# 4. 선택 결과에서 2017년 이동자수 상위 5개 지역을 출력하세요.
top5 = seoulDF.sort_values(by='2017', ascending=False).head(5)
display(top5[['2017']])

          2017
전입지별
전국     1571423
서울특별시  1018807
경기도     342433
인천광역시    40485
충청남도     21020